[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nfmix"
version = "0.1.0"
authors = [
  { name="Dimitrije Markovic"}
]
description = "Exploration of mixture of normalizing flows"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "zuko",
    "seaborn",
    "pyro-ppl",
    "torch-geometric",
    "torch-scatter"
    "ivon-opt"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "pre-commit",
    "ipykernel",
    "ipywidgets"
    # Add other dev tools if needed
]

[project.urls]
"Homepage" = "https://github.com/dimarkov/nfmix"
"Bug Tracker" = "https://github.com/dimarkov/nfmix/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/nfmix"]
